### ISSUE TITLE
当出现无效操作时还是会刷出新的2/4

### ISSUE THREAD

**Issue by on99-mielma** [DeeChael/LetsPlay2048#1]
![image](https://user-images.githubusercontent.com/76246048/184470734-3de4130a-feb7-4a2b-a432-a7cf0c5c27eb.png)
这时候按下左应该是不会有反应的
但按下后
![image](https://user-images.githubusercontent.com/76246048/184470751-3b3cdb85-7cf1-4882-b2f9-18061d3a0659.png)

**Comment by on99-mielma** [comment]
语言组织能力不是很行抱歉

**Comment by DeeChael** [comment]
抱歉这不是bug
虽然它无法移动，但是确实是那个方向移动了
故会刷新一个新的出来

**Comment by on99-mielma** [comment]
> 抱歉这不是bug 虽然它无法移动，但是确实是那个方向移动了 故会刷新一个新的出来

ok

**Comment by DeeChael** [comment]
啊不过，我可以在game中添加4个函数：
can_move_left
can_move_top
can_move_down
can_move_right
如果有人真的有需要可以自己改源码自己架设机器人
